export const FETCH_SIMPLE_DETAILS = 'FETCH_SIMPLE_DETAILS'
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'
export const FETCH_ROLES = 'FETCH_ROLES'


// User Personal Information
export const USER_INFO_SUCCESS = "USER_INFO_SUCCESS"
export const USER_INFO_FAIL = "USER_INFO_FAIL"

// Patients
export const FETCH_PATIENTS = "FETCH_PATIENTS"
export const FETCH_PATIENT_BY_ID = "FETCH_PATIENT_BY_ID"
export const FETCH_PATIENT_BY_NAME = "FETCH_PATIENT_BY_NAME"
export const POST_PATIENT = "POST_PATIENT"
export const PUT_PATIENT = "PUT_PATIENT"
export const PUT_PATIENT_BY_STATUS = 'PUT_PATIENT_BY_STATUS'

// Clients
export const FETCH_CLIENTS = 'FETCH_CLIENTS'
export const EMPTY_CLIENTS = 'EMPTY_CLIENTS'

//Langugages
export const FETCH_LANGUAGES = "FETCH_LANGUAGES"

// AppointmentType
export const FETCH_APPOINTMENT_TYPE = 'FETCH_APPOINTMENT_TYPE'

//Facility
export const FETCH_FACILITY_BY_CLIENT = "FETCH_FACILITY_BY_CLIENT"
export const EMPTY_FACILITY = "EMPTY_FACILITY"

//Buildings
export const FETCH_BUILDINGS_BY_FACILITY = "FETCH_BUILDINGS_BY_FACILITY"
export const EMPTY_BUILDING = "EMPTY_BUILDING"

// Appointments

export const FETCH_APPOINTMENTS = "FETCH_APPOINTMENTS"
export const POST_MULTIPLE_APPOINTMENTS = "POST_MULTIPLE_APPOINTMENTS"

// Interpreter
export const FETCH_INTERPRETER = "FETCH_INTERPRETER"

// DEPARTMENT

export const FETCH_DEPARTMENT_BY_BUILDING_ID = "FETCH_DEPARTMENT_BY_BUILDING_ID"
export const EMPTY_DEPARTMENT = "EMPTY_DEPARTMENT"

export const TEMP_APP_INFO = "TEMP_APP_INFO"
export const TEMP_APP_PATIENT_INFO = "TEMP_APP_PATIENT_INFO"